services:
  app:
    build:
      context: .
      target: dev  # ✅ Build the dev stage
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      MIX_ENV: dev
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_ORGANIZATION_KEY: "${OPENAI_ORGANIZATION_KEY}"
      OPENAI_API_URL: "${OPENAI_API_URL}"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/ask_flow_dev"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ask_flow_dev
    ports:
      - "5432:5432"
